version: '3.3'

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000  
      - PGID=1000  
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
      - WEBUI_USER=admin
      - WEBUI_PASS=j.Admin2709
    volumes:
      - ${APP_DATA}/qbittorrent/config:/config
      - ${MEDIA_FOLDER}:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped