version: '3.3'

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000  
      - PGID=1000  
      - TZ=Europe/Madrid  # Ajusta esto según tu zona horaria
      - WEBUI_PORT=8080
      - WEBUI_USER=admin  # Configurar el usuario del WebUI
      - WEBUI_PASS=j.Admin2709
    volumes:
      - /path/to/config:/config
      - /media/films/DiscoFilm:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped