version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${APP_DATA}/jellifin/config:/config
      - ${MEDIA_FOLDER}/movies:/media/movies
      - ${MEDIA_FOLDER}/shows:/media/shows
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped
