version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /media/films/jellifin-config:/config
      - /media/films/DiscoFilm:/media/movies
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped
